// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PULSE.Services.Data;

#nullable disable

namespace PULSE.Services.Migrations
{
    [DbContext(typeof(PULSEContext))]
    partial class PULSEContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PULSE.Services.Data.AvailableSize", b =>
                {
                    b.Property<int>("BicycleSizeId")
                        .HasColumnType("int")
                        .HasColumnName("BicycleSizeID");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("ProductID");

                    b.Property<int?>("AvailableQty")
                        .HasColumnType("int");

                    b.HasKey("BicycleSizeId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("AvailableSize", (string)null);
                });

            modelBuilder.Entity("PULSE.Services.Data.BicycleSize", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Size")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.ToTable("BicycleSize", (string)null);
                });

            modelBuilder.Entity("PULSE.Services.Data.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Brand", (string)null);
                });

            modelBuilder.Entity("PULSE.Services.Data.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordSalt")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("ShippingInfoId")
                        .HasColumnType("int")
                        .HasColumnName("ShippingInfoID");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Username")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ShippingInfoId");

                    b.ToTable("Customer", (string)null);
                });

            modelBuilder.Entity("PULSE.Services.Data.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("OrderID");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("ProductID");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetail", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("OrderDetail");
                });

            modelBuilder.Entity("PULSE.Services.Data.OrderHeader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("CustomerID");

                    b.Property<bool?>("Delivery")
                        .HasColumnType("bit");

                    b.Property<bool?>("OnlineOrder")
                        .HasColumnType("bit");

                    b.Property<string>("OrderNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("PaymentId")
                        .HasColumnType("int")
                        .HasColumnName("PaymentID");

                    b.Property<decimal?>("ShippingConst")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ShippingInfoId")
                        .HasColumnType("int")
                        .HasColumnName("ShippingInfoID");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TimeDelivered")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("TimePacked")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("TimeProcessed")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("TimeShipped")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PaymentId");

                    b.HasIndex("ShippingInfoId");

                    b.ToTable("OrderHeader", (string)null);
                });

            modelBuilder.Entity("PULSE.Services.Data.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Method")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("TimeOfPayment")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("Payment", (string)null);
                });

            modelBuilder.Entity("PULSE.Services.Data.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("BrandId")
                        .HasColumnType("int")
                        .HasColumnName("BrandID");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ProductCategoryId")
                        .HasColumnType("int")
                        .HasColumnName("ProductCategoryID");

                    b.Property<string>("ProductNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("ThumbImage")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("Product", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("Product");
                });

            modelBuilder.Entity("PULSE.Services.Data.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("ProductCategory", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("ProductCategory");
                });

            modelBuilder.Entity("PULSE.Services.Data.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("Data")
                        .HasColumnType("varbinary(max)");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("ProductID");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImage", (string)null);
                });

            modelBuilder.Entity("PULSE.Services.Data.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("PULSE.Services.Data.Servicing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("CustomerID");

                    b.Property<string>("CustomerRequest")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("LabourCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("OfferDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("OnlinePayment")
                        .HasColumnType("bit");

                    b.Property<int?>("PaymentId")
                        .HasColumnType("int")
                        .HasColumnName("PaymentID");

                    b.Property<string>("ServicingNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PaymentId");

                    b.ToTable("Servicing", (string)null);
                });

            modelBuilder.Entity("PULSE.Services.Data.ServicingPart", b =>
                {
                    b.Property<int>("ServicingId")
                        .HasColumnType("int")
                        .HasColumnName("ServicingID");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("ProductID");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ServicingId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("ServicingPart", (string)null);
                });

            modelBuilder.Entity("PULSE.Services.Data.ShippingInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Country")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StateOrProvince")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StreetAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.HasKey("Id");

                    b.ToTable("ShippingInfo", (string)null);
                });

            modelBuilder.Entity("PULSE.Services.Data.staff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DateOfEmployment")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordSalt")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Username")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Staff", (string)null);
                });

            modelBuilder.Entity("PULSE.Services.Data.Bicycle", b =>
                {
                    b.HasBaseType("PULSE.Services.Data.Product");

                    b.Property<int?>("ProductionYear")
                        .HasColumnType("int");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("WheelSize")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.HasIndex("ProductCategoryId");

                    b.HasDiscriminator().HasValue("Bicycle");
                });

            modelBuilder.Entity("PULSE.Services.Data.BicycleCategory", b =>
                {
                    b.HasBaseType("PULSE.Services.Data.ProductCategory");

                    b.HasDiscriminator().HasValue("Bicycle");
                });

            modelBuilder.Entity("PULSE.Services.Data.Gear", b =>
                {
                    b.HasBaseType("PULSE.Services.Data.Product");

                    b.Property<int?>("AvailableQty")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("int")
                        .HasColumnName("AvailableQty");

                    b.HasIndex("ProductCategoryId");

                    b.HasDiscriminator().HasValue("Gear");
                });

            modelBuilder.Entity("PULSE.Services.Data.GearCategory", b =>
                {
                    b.HasBaseType("PULSE.Services.Data.ProductCategory");

                    b.HasDiscriminator().HasValue("Gear");
                });

            modelBuilder.Entity("PULSE.Services.Data.OrderDetailBicycle", b =>
                {
                    b.HasBaseType("PULSE.Services.Data.OrderDetail");

                    b.Property<int?>("BicycleSizeId")
                        .HasColumnType("int")
                        .HasColumnName("BicycleSizeID");

                    b.HasIndex("BicycleSizeId");

                    b.HasDiscriminator().HasValue("Bicycle");
                });

            modelBuilder.Entity("PULSE.Services.Data.OrderDetailGear", b =>
                {
                    b.HasBaseType("PULSE.Services.Data.OrderDetail");

                    b.HasDiscriminator().HasValue("Gear");
                });

            modelBuilder.Entity("PULSE.Services.Data.OrderDetailPart", b =>
                {
                    b.HasBaseType("PULSE.Services.Data.OrderDetail");

                    b.HasDiscriminator().HasValue("Part");
                });

            modelBuilder.Entity("PULSE.Services.Data.Part", b =>
                {
                    b.HasBaseType("PULSE.Services.Data.Product");

                    b.Property<int?>("AvailableQty")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("int")
                        .HasColumnName("AvailableQty");

                    b.HasIndex("ProductCategoryId");

                    b.HasDiscriminator().HasValue("Part");
                });

            modelBuilder.Entity("PULSE.Services.Data.PartCategory", b =>
                {
                    b.HasBaseType("PULSE.Services.Data.ProductCategory");

                    b.HasDiscriminator().HasValue("Part");
                });

            modelBuilder.Entity("PULSE.Services.Data.AvailableSize", b =>
                {
                    b.HasOne("PULSE.Services.Data.BicycleSize", "BicycleSize")
                        .WithMany("AvailableSizes")
                        .HasForeignKey("BicycleSizeId")
                        .IsRequired()
                        .HasConstraintName("FK_AvailableSize_BicycleSize");

                    b.HasOne("PULSE.Services.Data.Bicycle", "Product")
                        .WithMany("AvailableSizes")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_AvailableSize_Bicycle");

                    b.Navigation("BicycleSize");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PULSE.Services.Data.Customer", b =>
                {
                    b.HasOne("PULSE.Services.Data.ShippingInfo", "ShippingInfo")
                        .WithMany("Customers")
                        .HasForeignKey("ShippingInfoId")
                        .HasConstraintName("FK_Customer_ShippingInfo");

                    b.Navigation("ShippingInfo");
                });

            modelBuilder.Entity("PULSE.Services.Data.OrderDetail", b =>
                {
                    b.HasOne("PULSE.Services.Data.OrderHeader", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("FK_OrderDetail_Order");

                    b.HasOne("PULSE.Services.Data.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK_OrderDetail_Product");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PULSE.Services.Data.OrderHeader", b =>
                {
                    b.HasOne("PULSE.Services.Data.Customer", "Customer")
                        .WithMany("OrderHeaders")
                        .HasForeignKey("CustomerId")
                        .HasConstraintName("FK_OrderHeader_Customer");

                    b.HasOne("PULSE.Services.Data.Payment", "Payment")
                        .WithMany()
                        .HasForeignKey("PaymentId")
                        .HasConstraintName("FK_OrderHeader_Payment");

                    b.HasOne("PULSE.Services.Data.ShippingInfo", "ShippingInfo")
                        .WithMany("OrderHeaders")
                        .HasForeignKey("ShippingInfoId")
                        .HasConstraintName("FK_OrderHeader_ShippingInfo");

                    b.Navigation("Customer");

                    b.Navigation("Payment");

                    b.Navigation("ShippingInfo");
                });

            modelBuilder.Entity("PULSE.Services.Data.Product", b =>
                {
                    b.HasOne("PULSE.Services.Data.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .HasConstraintName("FK_Product_Brand");

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("PULSE.Services.Data.ProductImage", b =>
                {
                    b.HasOne("PULSE.Services.Data.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK_ProductImage_Product");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PULSE.Services.Data.Servicing", b =>
                {
                    b.HasOne("PULSE.Services.Data.Customer", "Customer")
                        .WithMany("Servicings")
                        .HasForeignKey("CustomerId")
                        .HasConstraintName("FK_Servicing_Customer");

                    b.HasOne("PULSE.Services.Data.Payment", "Payment")
                        .WithMany()
                        .HasForeignKey("PaymentId")
                        .HasConstraintName("FK_Servicing_Payment");

                    b.Navigation("Customer");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("PULSE.Services.Data.ServicingPart", b =>
                {
                    b.HasOne("PULSE.Services.Data.Product", "Product")
                        .WithMany("ServicingParts")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_ServicingPart_Part");

                    b.HasOne("PULSE.Services.Data.Servicing", "Servicing")
                        .WithMany("ServicingParts")
                        .HasForeignKey("ServicingId")
                        .IsRequired()
                        .HasConstraintName("FK_ServicingPart_Servicing");

                    b.Navigation("Product");

                    b.Navigation("Servicing");
                });

            modelBuilder.Entity("PULSE.Services.Data.staff", b =>
                {
                    b.HasOne("PULSE.Services.Data.Role", "Role")
                        .WithMany("staff")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("FK_Staff_Role");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("PULSE.Services.Data.Bicycle", b =>
                {
                    b.HasOne("PULSE.Services.Data.BicycleCategory", "ProductCategory")
                        .WithMany("Bicycle")
                        .HasForeignKey("ProductCategoryId")
                        .HasConstraintName("FK_Product_ProductCategory");

                    b.Navigation("ProductCategory");
                });

            modelBuilder.Entity("PULSE.Services.Data.Gear", b =>
                {
                    b.HasOne("PULSE.Services.Data.GearCategory", "ProductCategory")
                        .WithMany("Gear")
                        .HasForeignKey("ProductCategoryId")
                        .HasConstraintName("FK_Product_ProductCategory");

                    b.Navigation("ProductCategory");
                });

            modelBuilder.Entity("PULSE.Services.Data.OrderDetailBicycle", b =>
                {
                    b.HasOne("PULSE.Services.Data.BicycleSize", "BicycleSize")
                        .WithMany("OrderDetails")
                        .HasForeignKey("BicycleSizeId")
                        .HasConstraintName("FK_OrderDetail_BicycleSize");

                    b.Navigation("BicycleSize");
                });

            modelBuilder.Entity("PULSE.Services.Data.Part", b =>
                {
                    b.HasOne("PULSE.Services.Data.PartCategory", "ProductCategory")
                        .WithMany("Part")
                        .HasForeignKey("ProductCategoryId")
                        .HasConstraintName("FK_Product_ProductCategory");

                    b.Navigation("ProductCategory");
                });

            modelBuilder.Entity("PULSE.Services.Data.BicycleSize", b =>
                {
                    b.Navigation("AvailableSizes");

                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("PULSE.Services.Data.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("PULSE.Services.Data.Customer", b =>
                {
                    b.Navigation("OrderHeaders");

                    b.Navigation("Servicings");
                });

            modelBuilder.Entity("PULSE.Services.Data.OrderHeader", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("PULSE.Services.Data.Product", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("OrderDetails");

                    b.Navigation("ServicingParts");
                });

            modelBuilder.Entity("PULSE.Services.Data.Role", b =>
                {
                    b.Navigation("staff");
                });

            modelBuilder.Entity("PULSE.Services.Data.Servicing", b =>
                {
                    b.Navigation("ServicingParts");
                });

            modelBuilder.Entity("PULSE.Services.Data.ShippingInfo", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("OrderHeaders");
                });

            modelBuilder.Entity("PULSE.Services.Data.Bicycle", b =>
                {
                    b.Navigation("AvailableSizes");
                });

            modelBuilder.Entity("PULSE.Services.Data.BicycleCategory", b =>
                {
                    b.Navigation("Bicycle");
                });

            modelBuilder.Entity("PULSE.Services.Data.GearCategory", b =>
                {
                    b.Navigation("Gear");
                });

            modelBuilder.Entity("PULSE.Services.Data.PartCategory", b =>
                {
                    b.Navigation("Part");
                });
#pragma warning restore 612, 618
        }
    }
}
